// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigortaAPI.Data;

#nullable disable

namespace SigortaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720084950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SigortaAPI.Models.Musteri", b =>
                {
                    b.Property<string>("MusteriNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriNo");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("SigortaAPI.Models.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<int>("CVC")
                        .HasColumnType("int");

                    b.Property<int>("KartNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("KulTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PoliceNo")
                        .HasColumnType("int");

                    b.HasKey("OdemeId");

                    b.HasIndex("MusteriNo");

                    b.HasIndex("PoliceNo");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("SigortaAPI.Models.Police", b =>
                {
                    b.Property<int>("PoliceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceNo"));

                    b.Property<DateTime>("BasTarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Bedel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BitTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("SigEttirenNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SigortaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TeklifDurum")
                        .HasColumnType("bit");

                    b.HasKey("PoliceNo");

                    b.HasIndex("SigEttirenNo");

                    b.HasIndex("SigortaNo");

                    b.ToTable("Policeler");
                });

            modelBuilder.Entity("SigortaAPI.Models.PoliceTeminat", b =>
                {
                    b.Property<int>("PoliceNo")
                        .HasColumnType("int");

                    b.Property<string>("TeminatKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Bedel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pirim")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PoliceNo", "TeminatKod");

                    b.HasIndex("TeminatKod");

                    b.ToTable("PoliceTeminatlari");
                });

            modelBuilder.Entity("SigortaAPI.Models.Teminat", b =>
                {
                    b.Property<string>("TeminatKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Pirim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeminatAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TeminatBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TeminatKod");

                    b.ToTable("Teminatlar");
                });

            modelBuilder.Entity("SigortaAPI.Models.Odeme", b =>
                {
                    b.HasOne("SigortaAPI.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaAPI.Models.Police", "Police")
                        .WithMany("Odemeler")
                        .HasForeignKey("PoliceNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Police");
                });

            modelBuilder.Entity("SigortaAPI.Models.Police", b =>
                {
                    b.HasOne("SigortaAPI.Models.Musteri", "SigEttirenMusteri")
                        .WithMany()
                        .HasForeignKey("SigEttirenNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigortaAPI.Models.Musteri", "SigortaliMusteri")
                        .WithMany("Policeler")
                        .HasForeignKey("SigortaNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SigEttirenMusteri");

                    b.Navigation("SigortaliMusteri");
                });

            modelBuilder.Entity("SigortaAPI.Models.PoliceTeminat", b =>
                {
                    b.HasOne("SigortaAPI.Models.Police", "Police")
                        .WithMany("PoliceTeminatlari")
                        .HasForeignKey("PoliceNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaAPI.Models.Teminat", "Teminat")
                        .WithMany("PoliceTeminatlari")
                        .HasForeignKey("TeminatKod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Police");

                    b.Navigation("Teminat");
                });

            modelBuilder.Entity("SigortaAPI.Models.Musteri", b =>
                {
                    b.Navigation("Policeler");
                });

            modelBuilder.Entity("SigortaAPI.Models.Police", b =>
                {
                    b.Navigation("Odemeler");

                    b.Navigation("PoliceTeminatlari");
                });

            modelBuilder.Entity("SigortaAPI.Models.Teminat", b =>
                {
                    b.Navigation("PoliceTeminatlari");
                });
#pragma warning restore 612, 618
        }
    }
}
