// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigortaAPI.Data;

#nullable disable

namespace SigortaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810103726_MusteriyeEmailEklendi")]
    partial class MusteriyeEmailEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SigortaAPI.Models.Musteri", b =>
                {
                    b.Property<string>("MusteriNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriNo");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("SigortaAPI.Models.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KulTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PoliceNo")
                        .HasColumnType("int");

                    b.Property<int>("TaksitSayisi")
                        .HasColumnType("int");

                    b.HasKey("OdemeId");

                    b.HasIndex("MusteriNo");

                    b.HasIndex("PoliceNo");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("SigortaAPI.Models.Police", b =>
                {
                    b.Property<int>("PoliceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceNo"));

                    b.Property<DateTime>("BasTarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Bedel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BeyanOnay")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BitTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("SigEttirenNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SigortaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TeklifDurum")
                        .HasColumnType("bit");

                    b.HasKey("PoliceNo");

                    b.HasIndex("SigEttirenNo");

                    b.HasIndex("SigortaNo");

                    b.ToTable("Policeler");
                });

            modelBuilder.Entity("SigortaAPI.Models.PoliceTeminat", b =>
                {
                    b.Property<int>("PoliceNo")
                        .HasColumnType("int");

                    b.Property<string>("TeminatKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Bedel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pirim")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PoliceNo", "TeminatKod");

                    b.HasIndex("TeminatKod");

                    b.ToTable("PoliceTeminatlari");
                });

            modelBuilder.Entity("SigortaAPI.Models.Teminat", b =>
                {
                    b.Property<string>("TeminatKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NetworkKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaketTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pirim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeminatAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TeminatBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TeminatKod");

                    b.ToTable("Teminatlar");

                    b.HasData(
                        new
                        {
                            TeminatKod = "TURKUAZ-Y4",
                            NetworkKod = "TURKUAZ",
                            PaketTipi = "Adet4",
                            Pirim = 9057.92m,
                            TeminatAd = "Turkuaz Network - Yatarak + Ayakta (4 Adet)",
                            TeminatBedeli = 100000m
                        },
                        new
                        {
                            TeminatKod = "TURKUAZ-Y10",
                            NetworkKod = "TURKUAZ",
                            PaketTipi = "Adet10",
                            Pirim = 13827.13m,
                            TeminatAd = "Turkuaz Network - Yatarak + Ayakta (10 Adet)",
                            TeminatBedeli = 100000m
                        },
                        new
                        {
                            TeminatKod = "TURKUAZ-YL",
                            NetworkKod = "TURKUAZ",
                            PaketTipi = "AdetLimitsiz",
                            Pirim = 17854.54m,
                            TeminatAd = "Turkuaz Network - Yatarak + Ayakta (Limitsiz Adet)",
                            TeminatBedeli = 100000m
                        },
                        new
                        {
                            TeminatKod = "TURUNCU-Y4",
                            NetworkKod = "TURUNCU",
                            PaketTipi = "Adet4",
                            Pirim = 10418.60m,
                            TeminatAd = "Turuncu Network - Yatarak + Ayakta (4 Adet)",
                            TeminatBedeli = 250000m
                        },
                        new
                        {
                            TeminatKod = "TURUNCU-Y10",
                            NetworkKod = "TURUNCU",
                            PaketTipi = "Adet10",
                            Pirim = 15473.38m,
                            TeminatAd = "Turuncu Network - Yatarak + Ayakta (10 Adet)",
                            TeminatBedeli = 250000m
                        },
                        new
                        {
                            TeminatKod = "TURUNCU-YL",
                            NetworkKod = "TURUNCU",
                            PaketTipi = "AdetLimitsiz",
                            Pirim = 19817.50m,
                            TeminatAd = "Turuncu Network - Yatarak + Ayakta (Limitsiz Adet)",
                            TeminatBedeli = 250000m
                        },
                        new
                        {
                            TeminatKod = "KIRMIZI-Y4",
                            NetworkKod = "KIRMIZI",
                            PaketTipi = "Adet4",
                            Pirim = 11306.92m,
                            TeminatAd = "Kırmızı Network - Yatarak + Ayakta (4 Adet)",
                            TeminatBedeli = 1000000m
                        },
                        new
                        {
                            TeminatKod = "KIRMIZI-Y10",
                            NetworkKod = "KIRMIZI",
                            PaketTipi = "Adet10",
                            Pirim = 16752.20m,
                            TeminatAd = "Kırmızı Network - Yatarak + Ayakta (10 Adet)",
                            TeminatBedeli = 1000000m
                        },
                        new
                        {
                            TeminatKod = "KIRMIZI-YL",
                            NetworkKod = "KIRMIZI",
                            PaketTipi = "AdetLimitsiz",
                            Pirim = 21439.63m,
                            TeminatAd = "Kırmızı Network - Yatarak + Ayakta (Limitsiz Adet)",
                            TeminatBedeli = 1000000m
                        });
                });

            modelBuilder.Entity("SigortaAPI.Models.Odeme", b =>
                {
                    b.HasOne("SigortaAPI.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaAPI.Models.Police", "Police")
                        .WithMany("Odemeler")
                        .HasForeignKey("PoliceNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Police");
                });

            modelBuilder.Entity("SigortaAPI.Models.Police", b =>
                {
                    b.HasOne("SigortaAPI.Models.Musteri", "SigEttirenMusteri")
                        .WithMany()
                        .HasForeignKey("SigEttirenNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigortaAPI.Models.Musteri", "SigortaliMusteri")
                        .WithMany("Policeler")
                        .HasForeignKey("SigortaNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SigEttirenMusteri");

                    b.Navigation("SigortaliMusteri");
                });

            modelBuilder.Entity("SigortaAPI.Models.PoliceTeminat", b =>
                {
                    b.HasOne("SigortaAPI.Models.Police", "Police")
                        .WithMany("PoliceTeminatlari")
                        .HasForeignKey("PoliceNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaAPI.Models.Teminat", "Teminat")
                        .WithMany("PoliceTeminatlari")
                        .HasForeignKey("TeminatKod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Police");

                    b.Navigation("Teminat");
                });

            modelBuilder.Entity("SigortaAPI.Models.Musteri", b =>
                {
                    b.Navigation("Policeler");
                });

            modelBuilder.Entity("SigortaAPI.Models.Police", b =>
                {
                    b.Navigation("Odemeler");

                    b.Navigation("PoliceTeminatlari");
                });

            modelBuilder.Entity("SigortaAPI.Models.Teminat", b =>
                {
                    b.Navigation("PoliceTeminatlari");
                });
#pragma warning restore 612, 618
        }
    }
}
